# Generated by Django 5.1 on 2024-12-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_colecao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colecao',
            options={'ordering': ('nome',)},
        ),
    ]
